# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapp.proto\x12\x03\x61pp\"\x1a\n\x07Request\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x19\n\x08Response\x12\r\n\x05reply\x18\x01 \x01(\t\":\n\x06Result\x12\x12\n\nevent_name\x18\x01 \x01(\t\x12\r\n\x05valid\x18\x02 \x01(\x08\x12\r\n\x05\x63ount\x18\x03 \x01(\x05\"*\n\nResultList\x12\x1c\n\x07results\x18\x01 \x03(\x0b\x32\x0b.app.Result2d\n\nAppService\x12*\n\x0bGetResponse\x12\x0c.app.Request\x1a\r.app.Response\x12*\n\tGetResult\x12\x0c.app.Request\x1a\x0f.app.ResultListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=18
  _globals['_REQUEST']._serialized_end=44
  _globals['_RESPONSE']._serialized_start=46
  _globals['_RESPONSE']._serialized_end=71
  _globals['_RESULT']._serialized_start=73
  _globals['_RESULT']._serialized_end=131
  _globals['_RESULTLIST']._serialized_start=133
  _globals['_RESULTLIST']._serialized_end=175
  _globals['_APPSERVICE']._serialized_start=177
  _globals['_APPSERVICE']._serialized_end=277
# @@protoc_insertion_point(module_scope)
